discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

releaseLanding:
    resource: "@ReleaseLandingBundle/Resources/config/routing.yml"
    prefix:   /

