releaseLanding_teamPage:
    path:    /team/
    defaults: { _controller: ReleaseLandingBundle:Home:team }

releaseLanding_homePage:
    path:    /
    defaults: { _controller: ReleaseLandingBundle:Home:index }
    
releaseLanding_recruitmentPage:
    path:    /recruitment/
    defaults: { _controller: ReleaseLandingBundle:Home:recruitment }  
    
